### ISSUE TITLE
Unable to run MovieLens10m Dataset

### ISSUE THREAD

**Issue by settyblue** [wei-tan/CuMF#9]
Hi Mr Tan,
We downloaded the movielens dataset from http://grouplens.org/datasets/movielens/10m/
We divideded the dataset into training and test dataset.
## Following is the metadata for that.

m,n = 71567, 65133
nnz in train = 9301274
## nnz in test = 698780 

(Just to inform : we were able to run your code on the netflix dataset successfully.)
We tried running your code for the the above dataset but we are getting the following output:
./main 10 0.1 1
F = 10, lambda = 0.1, THETA_BATCH = 1 
******_starting loading training and testing sets to host.
***_**_parameters: m: 71567, n:  65133, f: 10, nnz: 9301274 
***_**_start allocating memory on GPU...
***_***start copying memory to GPU...
--------- Train RMSE in iter 0: nan
--------- Test RMSE in iter 0: nan
--------- Train RMSE in iter 1: nan
--------- Test RMSE in iter 1: nan
--------- Train RMSE in iter 2: nan
--------- Test RMSE in iter 2: nan
--------- Train RMSE in iter 3: nan
--------- Test RMSE in iter 3: nan
--------- Train RMSE in iter 4: nan
--------- Test RMSE in iter 4: nan
--------- Train RMSE in iter 5: nan
--------- Test RMSE in iter 5: nan
--------- Train RMSE in iter 6: nan
--------- Test RMSE in iter 6: nan
--------- Train RMSE in iter 7: nan
--------- Test RMSE in iter 7: nan
--------- Train RMSE in iter 8: nan
--------- Test RMSE in iter 8: nan
--------- Train RMSE in iter 9: nan
--------- Test RMSE in iter 9: nan

doALS takes seconds: 3.000 for F= 10

ALS Done.

**Comment by wei-tan** [comment]
Hi, we used to hard code a lot of parameters specific to netflix. In the latest push we fixed that. 
To run movielens 10m:

cd ./data/ml10M
ipython prepare_ml10M_data.py

After the data is generated, run:

./main 71567 65133 100 9000048 1000006 0.03 1 1 ./data/ml10M

wtan@digits01:~/gpu/git/CuMF$ ./main 71567 65133 100 9000048 1000006 0.03 1 1 ./data/ml10M
M = 71567, N = 65133, F = 100, NNZ = 9000048, NNZ_TEST = 1000006, lambda = 0.030000
X_BATCH = 1, THETA_BATCH = 1
DATA_DIR = ./data/ml10M
******_start loading training and testing sets to host.
***_**_parameters: m: 71567, n:  65133, f: 100, nnz: 9000048
***_**_start allocating memory on GPU...
***_***start copying memory to GPU...
--------- Train RMSE in iter 0: 1.087894
--------- Test RMSE in iter 0: 0.910956
--------- Train RMSE in iter 1: 1.163193
--------- Test RMSE in iter 1: 0.874528
--------- Train RMSE in iter 2: 1.169236
--------- Test RMSE in iter 2: 0.842969
--------- Train RMSE in iter 3: 1.174273
--------- Test RMSE in iter 3: 0.833294
--------- Train RMSE in iter 4: 1.176888
--------- Test RMSE in iter 4: 0.829037
--------- Train RMSE in iter 5: 1.178118
--------- Test RMSE in iter 5: 0.827072
--------- Train RMSE in iter 6: 1.178339
--------- Test RMSE in iter 6: 0.826137
--------- Train RMSE in iter 7: 1.178254
--------- Test RMSE in iter 7: 0.825568
--------- Train RMSE in iter 8: 1.178026
--------- Test RMSE in iter 8: 0.825254
--------- Train RMSE in iter 9: 1.177727
--------- Test RMSE in iter 9: 0.825028

doALS takes seconds: 15.371 for F = 100

ALS Done.

**Comment by settyblue** [comment]
Thanks a Lot for the support!

**Comment by settyblue** [comment]
Hi we ran the latest code, but We are still facing the issue.
Please help us out.

$ ./main 71567 65133 100 9000048 1000006 0.03 1 1 ./data/ml10M/
M = 71567, N = 65133, F = 100, NNZ = 9000048, NNZ_TEST = 1000006, lambda = 0.030000
X_BATCH = 1, THETA_BATCH = 1
DATA_DIR = ./data/ml10M/ 
******_start loading training and testing sets to host.
***_**_parameters: m: 71567, n:  65133, f: 100, nnz: 9000048 
***_**_start allocating memory on GPU...
***_***start copying memory to GPU...
--------- Train RMSE in iter 0: 1.089565
--------- Test RMSE in iter 0: nan
--------- Train RMSE in iter 1: 2.826091
--------- Test RMSE in iter 1: nan
--------- Train RMSE in iter 2: 111.067947
--------- Test RMSE in iter 2: nan
--------- Train RMSE in iter 3: nan
--------- Test RMSE in iter 3: nan
--------- Train RMSE in iter 4: nan
--------- Test RMSE in iter 4: nan
--------- Train RMSE in iter 5: nan
--------- Test RMSE in iter 5: nan
--------- Train RMSE in iter 6: nan
--------- Test RMSE in iter 6: nan
--------- Train RMSE in iter 7: nan
--------- Test RMSE in iter 7: nan
--------- Train RMSE in iter 8: nan
--------- Test RMSE in iter 8: nan
--------- Train RMSE in iter 9: nan
--------- Test RMSE in iter 9: nan

doALS takes seconds: 18.527 for F = 100

ALS Done.

**Comment by wei-tan** [comment]
Could you change lambda from 0.03 to 0.05?
Also, could you uncomment in als.cu  the line #define SURPASS_NAN, as suggested in README?
